services:
  app:
    build: .
    env_file: .env
    stdin_open: true
    enivronment:
      MONGO_URI: mongodb://host.docker.internal:27017
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"